# Domain where integrity will be running from. This is used to have
# nice URLs in your notifications.
# For example:
#   http://builder.integrityapp.com
:base_uri: http://integrity.domain.tld

# This should be a complete connection string to your database.
#
# Examples:
# * `mysql://user:password@localhost/integrity`
# * `postgres://user:password@localhost/integrity`
# * `sqlite3:///home/integrity/db/integrity.sqlite`
#
# Note:
# * The appropriate data_objects adapter must be installed (`do_mysql`, etc)
# * You must create the `integrity` database on localhost, of course.
:database_uri: sqlite3:///var/integrity.db

# This is where your project's code will be checked out to. Make sure it's
# writable by the user that runs Integrity.
:export_directory: /path/to/scm/exports

# Path to the integrity log file
:log: /var/log/integrity.log

# If set to true integrity will do a build for each commit.  Otherwise
# it will only do a build for each set of commits (i.e. each push)
:build_all_commits: true

# Enable or disable HTTP authentication for the app. BE AWARE that if you
# disable this anyone can delete and alter projects, so do it only if your
# app is running in a controlled environment (ie, behind your company's
# firewall.)
:use_basic_auth: false

# When `use_basic_auth` is true, the admin's username for HTTP authentication.
:admin_username: username

# When `use_basic_auth` is true, the admin's password. Usually saved as a
# SHA1 hash. See the next option.
:admin_password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

# If this is true, then whenever we authenticate the admin user, will hash
# it using SHA1. If not, we'll assume the provided password is in plain text.
:hash_admin_password: true
